### PR TITLE
Refactor and more (MQTT)

### PR DESCRIPTION
**Pull request by edenhaus**
- Removed unused dependencies
- Removed all XMPPError as this error will be never thrown (will only be thrown by communicating with XMPP, which we will not support)
- Removed encrypt method as it will not longer be used
- Removed country_alpha2_to_continent_code to remove used dependency. The cli is fore sure not used often, therefore I decided to not include a dependency for a default option. User needs to specify like in HA country and continent
- Reformat the whole code and fix some common lint errors
- Remove travis.yaml as we do not use it
- Refactored EcovacsApi and moved it also in separate file
- Refactored EcoVacsJson
- Refactored VacBot into separate file
- Refactored event handling
- Refactored Map, moved map event into the Map class
- Removed cli
- Remvoed appveyor.yml
- **Use asyncio and aiohttp**
- **Add MQTT**

### CODE REVIEW

**Comment by And3rsL** [comment]
> * Removed unused dependencies
> * Removed all XMPPError as this error will be never thrown (will only be thrown by communicating with XMPP, which we will not support)
> * Removed encrypt method as it will not longer be used
> * Removed country_alpha2_to_continent_code to remove used dependency. The cli is fore sure not used often, therefore I decided to not include a dependency for a default option. User needs to specify like in HA country and continent
> * Reformat the whole code and fix some common lint errors
> * Remove travis.yaml as we do not use it
> * Refactored EcovacsApi and moved it also in separate file
> 
> @And3rsL do we really need the cli?
> I think also appveyor.yml is not used or I'm wrong?

Yes, some people is using this.. we should keep it

Anyway great work!!!

**Comment by edenhaus** [comment]
Still some parts to do. Finishing handling events and then refactor the map.

I removed completely the scheduling functionality as it was error prone and Home Assistant has support for scheduling (polling at specific interval). I suggest we should use it.

**Comment by edenhaus** [comment]
> > * Removed unused dependencies
> > * Removed all XMPPError as this error will be never thrown (will only be thrown by communicating with XMPP, which we will not support)
> > * Removed encrypt method as it will not longer be used
> > * Removed country_alpha2_to_continent_code to remove used dependency. The cli is fore sure not used often, therefore I decided to not include a dependency for a default option. User needs to specify like in HA country and continent
> > * Reformat the whole code and fix some common lint errors
> > * Remove travis.yaml as we do not use it
> > * Refactored EcovacsApi and moved it also in separate file
> > 
> > @And3rsL do we really need the cli?
> > I think also appveyor.yml is not used or I'm wrong?
> 
> Yes, some people is using this.. we should keep it
> 
> Anyway great work!!!

I removed the cli as we must rewrite it completely as there exists only events. As this is a library, we only provide the python code. As other projects someone can use it and create a cli

**Comment by edenhaus** [comment]
@And3rsL can you please upload this changes to `deebotozmo-beta`. So I can start to adopt https://github.com/And3rsL/Deebot-for-Home-Assistant

**Comment by Pr0mises** [comment]
Nice refactor. I'll wait till it's finished before starting to work on XML support, could you give me like an entrance which I can use to specify if the robot should use json or xml? If not that's fine I'll do it myself.

In my research why my robot just doesn't work with any python library, I found a working[ JS library](https://github.com/mrbungle64/ecovacs-deebot.js) which supports way more robots than this one, after comparing the code and reading some issues it looks like @And3rsL converted the JS library to python but sadly only the JSON part

**Comment by edenhaus** [comment]
> Nice refactor. I'll wait till it's finished before starting to work on XML support, could you give me like an entrance which I can use to specify if the robot should use json or xml? If not that's fine I'll do it myself.

@Pr0mises We can talk about, when the whole refactoring is finished. Today I have added the MQTT support, which will reduce the requests we will made... I had to add it directly in this PR as the whole refactoring with async introduced a new problem. The vacuum can handle only a certain amount of parallel requests...

> In my research why my robot just doesn't work with any python library (spoiler: every library uses sucks but it's archived), I found a working[ JS library](https://github.com/mrbungle64/ecovacs-deebot.js) which supports way more robots than this one, after comparing the code and reading some issues it looks like @And3rsL converted the JS library to python but sadly only the JSON part

I already know this library and we are also sharing information between. I must defend Andrea, that we can only give support to devices we own (Currently the 950, which supports json). We don't convert/add code without the possibility to test it....

**Comment by Pr0mises** [comment]
@edenhaus Ye sure I understand why he didn't support it beforehand. I own a deebot slim 10 and will wait till it's finished and try my best to implement xml.

**Comment by edenhaus** [comment]
@And3rsL it's time to test it :) I would create a pre-release for both the library and component so advanced user can test it.

Can you please create a new pre-release version of `deebotozmo`. See https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning
I would not use the package `deebotozmo-beta` as it is no so clear for other users of the libray (my opinion).

I would create the new version `2.0.0b1` so everyone can see that it's a big jump
What do you think?

**Comment by And3rsL** [comment]
> @And3rsL it's time to test it :) I would create a pre-release for both the library and component so advanced user can test it.
> 
> Can you please create a new pre-release version of `deebotozmo`. See https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning
> I would not use the package `deebotozmo-beta` as it is no so clear for other users of the libray (my opinion).
> 
> I would create the new version `2.0.0b1` so everyone can see that it's a big jump
> What do you think?

im looking forward to test it!!
just released! 😄 
https://pypi.org/project/deebotozmo/2.0.0b1/

**Comment by edenhaus** [comment]
closing and going on in #37

**Pull request closed without merging**
